#  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a = 1
b = 2
even_sum = 0

while True:
    c = a+b
    rem = b % 2
    if b > 4*pow(10,6):
        break
    if rem == 0:
        even_sum = even_sum + b
    a = b
    b = c

print("Answer: " + str(even_sum))
